# Generated by Django 3.2.9 on 2021-11-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DnaRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna', models.JSONField()),
                ('mutation', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'DNA',
                'verbose_name_plural': 'DNAs',
                'ordering': ('create_date',),
            },
        ),
    ]
